/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.xtracise;
import com.xtracise.models.Exercici;
import com.xtracise.models.Usuari;
import com.xtracise.models.Workout;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author aaron
 */
public class CreateWorkoutDialog extends javax.swing.JDialog {

    private Usuari user;
    private boolean successful = false;
    private DefaultListModel<Exercici> exercicisModel;

    /**
     * Creates new form CreateWorkoutDialog
     */
    public CreateWorkoutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public CreateWorkoutDialog(java.awt.Frame parent, boolean modal, Usuari user) {
        super(parent, modal);
        initComponents();
        this.user = user;
        this.exercicisModel = new DefaultListModel<>();
        setupData();
    }

    public boolean isSuccessful() {
        return successful;
    }

    private void setupData() {
        jtfDate.setText(java.time.LocalDate.now().toString());

        ArrayList<Exercici> exercicis = DataAccess.getAllExercicis();
        for (Exercici ex : exercicis) {
            exercicisModel.addElement(ex);
        }
        jlExercicis.setModel(exercicisModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSave = new javax.swing.JButton();
        jlDate = new javax.swing.JLabel();
        jspScroll = new javax.swing.JScrollPane();
        jlExercicis = new javax.swing.JList<>();
        jtfDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbSave.setText("Save");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jlDate.setText("Date");

        jlExercicis.setModel(new javax.swing.AbstractListModel<Exercici>() {
            Exercici[] exercicis = { };
            public int getSize() { return exercicis.length; }
            public Exercici getElementAt(int i) { return exercicis[i]; }
        });
        jspScroll.setViewportView(jlExercicis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jbSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jlDate)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jspScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDate)
                    .addComponent(jspScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jbSave)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        try {
            Workout workout = new Workout();
            workout.setForDate(jtfDate.getText());
            workout.setIdUsuari(user.getId());

            ArrayList<Exercici> selectedExercises = new ArrayList<>(jlExercicis.getSelectedValuesList());

            DataAccess.insertWorkout(workout, selectedExercises);

            successful = true;
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving workout");
        }
    }//GEN-LAST:event_jbSaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlDate;
    private javax.swing.JList<Exercici> jlExercicis;
    private javax.swing.JScrollPane jspScroll;
    private javax.swing.JTextField jtfDate;
    // End of variables declaration//GEN-END:variables
}
